trigger:
- main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      workingDirectory: 'src/GameTrilha.API'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'backend-app-publish'
      publishLocation: 'Container'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students(c4bd49c2-9484-41dd-aa89-9054aee0bc1e)'
      appType: 'webAppLinux'
      appName: 'trilha-hmg'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      runtimeStack: 'DOTNETCORE|7.0'